name: Docker Image CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file \src\web-app-with-authentication\Dockerfile.buildPublish --label buildPublishResult:${{ github.event.repository.updated_at}} --progress=plain --no-cache
