name: Docker Image CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.buildPublish --label buildPublishResult:$(date +%s) --progress=plain --no-cache
